### ISSUE TITLE
operator from Readme.md gives error

### ISSUE THREAD

**Issue by HoffiMuc** [cloudfoundry-community/jumpbox-boshrelease#74]
I am trying to setup a jumpbox with cpi vsphere and bucc bosh (on opsman vm 2.7.6)

```
---
- type: replace
  path: /instance_groups/name=jumpbox/jobs/name=jumpbox/properties/users/-
  value:
    name:  jumper                  # creates an account named `my-user-1`
    shell: /bin/bash                  # sets the account's shell to bash
    ssh_keys:
      - ssh-rsa <my public key>
```

`bosh -e malbec_bucc -d jumpbox deploy manifests/jumpbox.yml -o ops/10_jumpbox-op-original.yml`

```
Using deployment 'jumpbox'

Evaluating manifest:
  Error 'operation [0] in ops/10_jumpbox-op-original.yml failed': Expected to find a map key 'properties' for path '/instance_groups/name=jumpbox/jobs/name=jumpbox/properties' (found map keys: 'name', 'release')

Exit code 1
```

I also tried with a modified operator, which succeeds, but afterwards I cannot login to my jumpbox:

```
ubuntu@opsmanager:~/jumpbox-boshrelease$ ssh jumper@10.0.2.7
Unauthorized use is strictly prohibited. All access and activity
is subject to logging and monitoring.
jumper@10.0.2.7's password:
Permission denied, please try again.
```

I do not expect having to give a password. (also fails if I add a `password: mypass` property to the user)

ssh -vv ...

```
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug2: set_newkeys: mode 0
debug1: rekey after 4294967296 blocks
debug2: key: /home/ubuntu/.ssh/malbec (0x55fa5253da70), explicit
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<rsa-sha2-256,rsa-sha2-512>
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
Unauthorized use is strictly prohibited. All access and activity
is subject to logging and monitoring.
debug1: Authentications that can continue: publickey,password
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /home/ubuntu/.ssh/malbec
debug2: we sent a publickey packet, wait for reply
debug1: Authentications that can continue: publickey,password
debug2: we did not send a packet, disable method
debug1: Next authentication method: password
```

the operator I used was:

```
---
- type: replace
  path: /name
  value: jumpbox

- type: remove
  path: /properties

- type: replace
  path: /instance_groups/name=jumpbox/jobs/name=jumpbox/properties?/env?
  value:
    FOO: BAR

- type: replace
  path: /instance_groups/name=jumpbox/jobs/name=jumpbox/properties?/users?
  value:
  - name:  jumper                     # creates an account named 'jumper'
    shell: /bin/bash                  # sets the account's shell to bash
    env:   https://github.com/hoffipublic/jumpbox-boshrelease-env.git  # clones a git repo of an environment to `~/env`
                                      # and runs `./install` from inside the repo, as the user
    setup_script: ~/env/setup.sh      # runs after account creation, and environment
                                      # installation. the default value runs a script
                                      # to set up rvm and install some ruby gems we find useful
    ssh_keys:
    - ssh-rsa asdlfjkasdfjasasdfasdfasdf
```

any ideas what went wrong?
