### ISSUE TITLE
Malformed add-user-op.yml example ops-file

### ISSUE THREAD

**Issue by davewalter** [cloudfoundry-community/jumpbox-boshrelease#81]
There was an [interrupt](https://cloudfoundry.slack.com/archives/C02FL4A2K/p1606930424193100) in the #general channel of the Cloud Foundry slack instance asking for help in using the add-user-op.yml ops-file. 

It looks like the [current example file](https://github.com/cloudfoundry-community/jumpbox-boshrelease/blob/caf38151f81688236271753f28249d415d64629d/manifests/add-user-op.yml) has been accidentally changed by release automation and now contains the contents of the release section of the manifest, instead of the example values required to add a user to the jumpbox VM. For comparison, here are the [original contents of the file](https://github.com/cloudfoundry-community/jumpbox-boshrelease/blob/e3150308cd155242b4b80dee3c7236fbe5c80356/manifests/add-user-op.yml):
```yaml
---
# this is a BOSH Ops file, to be applied with the
# `bosh deploy -o ...` command:
- type: replace
  path: /instance_groups/name=jumpbox/jobs/name=jumpbox/properties?/jumpbox?/users?/-
  value:
    name:  user
    shell: /bin/bash
    ssh_keys:
      - ssh-ed25519 ...
```
It would be great if the original example could be restored and the automation fixed to not update it.
